matrix:
  include:    
    - language: c  
      sudo: false # only for faster builds  
      compiler:
        - clang
        - gcc
      script:  
        - gcc -o abhijit abhijit.c 
        - ./abhijit
        - gcc -o pooja pooja.c
        - ./pooja
        - gcc -o aish aish.c
        - ./aish
    

 
